//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.13 at 11:35:07 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://code.google.com/p/simplenlg/schemas/version1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package simplenlg.xmlrealiser.wrapper;
