//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.13 at 11:35:07 AM CEST 
//


package simplenlg.xmlrealiser.wrapper;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PhraseElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PhraseElement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://code.google.com/p/simplenlg/schemas/version1}NLGElement">
 *       &lt;sequence>
 *         &lt;element name="frontMod" type="{http://code.google.com/p/simplenlg/schemas/version1}NLGElement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="preMod" type="{http://code.google.com/p/simplenlg/schemas/version1}NLGElement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="head" type="{http://code.google.com/p/simplenlg/schemas/version1}WordElement" minOccurs="0"/>
 *         &lt;element name="compl" type="{http://code.google.com/p/simplenlg/schemas/version1}NLGElement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="postMod" type="{http://code.google.com/p/simplenlg/schemas/version1}NLGElement" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="cat" type="{http://code.google.com/p/simplenlg/schemas/version1}phraseCategory" />
 *       &lt;attribute name="discourseFunction" type="{http://code.google.com/p/simplenlg/schemas/version1}discourseFunction" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhraseElement", propOrder = {
    "frontMod",
    "preMod",
    "head",
    "compl",
    "postMod"
})
@XmlSeeAlso({
    PPPhraseSpec.class,
    AdjPhraseSpec.class,
    AdvPhraseSpec.class,
    NPPhraseSpec.class,
    VPPhraseSpec.class,
    SPhraseSpec.class
})
public abstract class PhraseElement
    extends NLGElement
{

    protected List<NLGElement> frontMod;
    protected List<NLGElement> preMod;
    protected WordElement head;
    protected List<NLGElement> compl;
    protected List<NLGElement> postMod;
    @XmlAttribute
    protected PhraseCategory cat;
    @XmlAttribute
    protected DiscourseFunction discourseFunction;

    /**
     * Gets the value of the frontMod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the frontMod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFrontMod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NLGElement }
     * 
     * 
     */
    public List<NLGElement> getFrontMod() {
        if (frontMod == null) {
            frontMod = new ArrayList<NLGElement>();
        }
        return this.frontMod;
    }

    /**
     * Gets the value of the preMod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the preMod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPreMod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NLGElement }
     * 
     * 
     */
    public List<NLGElement> getPreMod() {
        if (preMod == null) {
            preMod = new ArrayList<NLGElement>();
        }
        return this.preMod;
    }

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link WordElement }
     *     
     */
    public WordElement getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link WordElement }
     *     
     */
    public void setHead(WordElement value) {
        this.head = value;
    }

    /**
     * Gets the value of the compl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NLGElement }
     * 
     * 
     */
    public List<NLGElement> getCompl() {
        if (compl == null) {
            compl = new ArrayList<NLGElement>();
        }
        return this.compl;
    }

    /**
     * Gets the value of the postMod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the postMod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPostMod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NLGElement }
     * 
     * 
     */
    public List<NLGElement> getPostMod() {
        if (postMod == null) {
            postMod = new ArrayList<NLGElement>();
        }
        return this.postMod;
    }

    /**
     * Gets the value of the cat property.
     * 
     * @return
     *     possible object is
     *     {@link PhraseCategory }
     *     
     */
    public PhraseCategory getCat() {
        return cat;
    }

    /**
     * Sets the value of the cat property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhraseCategory }
     *     
     */
    public void setCat(PhraseCategory value) {
        this.cat = value;
    }

    /**
     * Gets the value of the discourseFunction property.
     * 
     * @return
     *     possible object is
     *     {@link DiscourseFunction }
     *     
     */
    public DiscourseFunction getDiscourseFunction() {
        return discourseFunction;
    }

    /**
     * Sets the value of the discourseFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiscourseFunction }
     *     
     */
    public void setDiscourseFunction(DiscourseFunction value) {
        this.discourseFunction = value;
    }

}
